homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 12
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
    media_player.receiver:
      friendly_name: Onkyo | Reciever

# Show links to resources in log and frontend
# introduction:

hassio:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:
recorder:

#device_tracker:
#  - platform: bluetooth_tracker
#    name: Jeroen
#    mac: !secret mac_jeroen
#    interval_seconds: 10
#    consider_home: 180
#  - platform: bluetooth_tracker
#    name: Tobias
#    mac: !secret mac_tobias
#    interval_seconds: 10
#    consider_home: 180

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Text to speech
#tts:
#  platform: google

media_player:
  - platform: onkyo
    host: !secret onkyoip
    name: receiver
    sources:
      pc: 'HTPC'
  - platform: samsungtv
    host: !secret samsungip
    port: 8001

rfxtrx:
  device: /dev/ttyUSB0
#  debug: True
  dummy: False

hue:
  bridges:
    - host: !secret hueip
      allow_unreachable: true
      allow_hue_groups: true

light:
  - platform: flux_led
    devices: 
      10.0.1.4:
        name: cornerlight 
        mode: "rgbw"

switch:
  platform: rfxtrx
  automatic_add: True
  devices:
    0b11000d0129019e0a010f60:
      name: Motion_kaku_living
    0b11005b01a3222601000070:
      name: Kerstboom_PW
    0b11005e01a3222602010f70:
      name: Overig_PW
    0b11005f01a3222603010f70:
      name: Samsung_PW
    0b1100030155861a02010f70:
      name: Douche_Ventilatie
#    0b1100b5008b25e202000050:
#      name: Motion_Toilet

#binary_sensor:
#  platform: rfxtrx
#  automatic_add: True


telegram_bot:
  - platform: broadcast
    api_key: !secret telegrambotjeroen
    allowed_chat_ids:
      - !secret chatidbarentszstraat
      - !secret chatidplantsjeroen

notify:
  - name: Plant_Notifications_Barentszstraat
    platform: telegram
    chat_id: !secret chatidbarentszstraat

group: !include_dir_merge_named group/
sensor: !include_dir_merge_list sensor/
automation: !include_dir_merge_list automation/
scene: !include_dir_merge_list scene/
script: !include_dir_merge_named script/
