homeassistant:
  # Name of the location where Home Assistant is running
  name: 4th Floor
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 12
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize:
    media_player.receiver:
      friendly_name: Onkyo | Reciever

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Text to speech
tts:
  platform: google

media_player:
  - platform: onkyo
    host: !secret onkyoip
    name: receiver
    sources:
      pc: 'HTPC'
  - platform: samsungtv
    host: !secret samsungip

ios:

light:
  - platform: flux_led
    devices: 
      10.0.1.4:
        name: cornerlight 
        mode: "rgbw"

group: !include_dir_merge_named group/
sensor: !include_dir_merge_list sensor/
automation: !include_dir_merge_list automation/
scene: !include_dir_merge_list scene/
script: !include_dir_merge_list script/
