#################################################################
## Scripts Living Corner Switch
#################################################################

- platform: template
  switches:
    skylight:
      value_template: "{{ is_state('script.living_cornerlight_plantssignalon', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.watersignal_on
      turn_off:
        service: switch.turn_on
        data:
          entity_id: switch.watersignal_off