#################################################################
## Scripts Living Corner Switch
#################################################################

- platform: template
  switches:
    plantsignal:
      value_template: "{{ is_state('sensor.living_cornerlight_plantssignalon', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.watersignal_on
      turn_off:
        service: switch.turn_on
        data:
          entity_id: switch.watersignal_off

- platform: template
  switches:
    netflixsignal:
      value_template: "{{ is_state('sensor.living_light_netflix', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.netfixsignal_on
      turn_off:
        service: switch.turn_on
        data:
          entity_id: switch.netlixsignal_off

- platform: template
  switches:
    batterysignal:
      value_template: "{{ is_state('sensor.empty_batterys_signalon', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.batterysignal_on
      turn_off:
        service: switch.turn_on
        data:
          entity_id: switch.batterysignal_off