#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
  devices:
    0a520701720e00ba390159:
      name: BathHydro
      data_type:
        - Humidity
        - Temperature
        - Sensor Status
    0b1100030155861a02010f70:
      name: Douche_Ventilatie

- alias: Mosquito bedroom on
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.cornerlight_pw

- alias: BedMosquito bedroom off
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.cornerlight_pw