#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
  devices:
    0a520701720e00ba390159:
      name: BathHydro
      data_type:
        - Humidity
        - Temperature
        - Sensor Status
    0b1100030155861a02010f70:
      name: Douche_Ventilatie