#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
#  automatic_add: True
  devices:
    0a520701720e00ba390159:
      name: BathHydro
      data_type:
        - Humidity
        - Temperature
        - Sensor Status

- platform: statistics
  name: Humidity_stats
  entity_id: sensor.bathhydro_humidity
  data_type:
    - min_value
  max_age:
    minutes: 90