#################################################################
## Sensors Plants Climate
#################################################################

- platform: miflora
  mac: 'C4:7C:8D:66:1F:BE'
  name: Polyscias Fruticosa
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery


- platform: miflora
  mac: 'C4:7C:8D:65:D2:FC'
  name: Dieffenbachia
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:65:D2:7D'
  name: Yukka Eliphantipes
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:65:D2:F2'
  name: Musa Banana
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:65:D2:F7'
  name: Ficus Elastica
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:65:D2:21'
  name: Aeschynanthus
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:7C:8D:65:D2:F3'
  name: Croton
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: 'C4:C1:B4:87:62:75'
  name: Ficus Benjamina
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery