#################################################################
## Sensors Plants Climate
#################################################################

- platform: miflora
  mac: 'C4:7C:8D:66:1F:BE'
  name: Polyscias Fruticosa
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery


- platform: miflora
  mac: 'C4:7C:8D:65:D2:FC'
  name: Dieffenbachia
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery