#################################################################
## Sensors Plants Climate
#################################################################

- platform: miflora
  mac: 'C4:7C:8D:66:1F:BE'
  name: Polyscias Fruticosa
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery