#################################################################
## Sensors Toilet Motion
#################################################################

- platform: rfxtrx
  devices:
    0b1100b5008b25e202000050:
      name: Toilet Motion
      device_class: motion
      off_delay:
        seconds: 5