#################################################################
## Automation Hue Kitchen
#################################################################

- alias: Kitchen playing netflix motion sensor
  trigger:
    - platform: state
      entity_id: 'light.keuken'
      from: "on"
      to: "off"
    - platform: state
      to: 'playing'
      entity_id: media_player.entertainment_area
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: template
            value_template: >-
              {%- if is_state_attr("media_player.entertainment_area", "app_name", "Netflix") -%}
                true
              {%- endif -%}
          - condition: template
            value_template: >-
              {%- if is_state_attr("media_player.entertainment_area", "app_name", "Default Media Receiver") -%}
                true
              {%- endif -%}
          - condition: template
            value_template: >-
              {%- if is_state_attr("media_player.entertainment_area", "app_name", "Ziggo GO") -%}
                true
              {%- endif -%}
          - condition: template
            value_template: >-
              {%- if is_state_attr("media_player.entertainment_area", "app_name", "Pathé Thuis") -%}
                true
              {%- endif -%}
          - condition: template
            value_template: >-
              {%- if is_state_attr("media_player.entertainment_area", "app_name", "Youtube") -%}
                true
              {%- endif -%}
          - condition: template
            value_template: >-
              {%- if is_state_attr("media_player.entertainment_area", "app_name", "Videostream'") -%}
                true
              {%- endif -%}
  action:
    service: script.turn_on
    entity_id: script.kitchen_netflix