#################################################################
## Sensors Cornerlight Sensor
#################################################################

- platform: template
  sensors:
    cornerlight_color_status:
      friendly_name: "Cornerlight Color Status"
      value_template: >-
        {% if is_state_attr("media_player.chromecastultra8714", "app_name", "Netflix") %}
          video
        {% elif is_state_attr("media_player.chromecastultra8714", "app_name", "Default Media Receiver") %}
          video
        {% elif is_state_attr("media_player.chromecastultra8714", "app_name", "Ziggo GO") %}
          video
        {% elif is_state_attr("media_player.chromecastultra8714", "app_name", "Pathé Thuis") %}
          video
        {% elif is_state_attr("media_player.chromecastultra8714", "app_name", "Youtube") %}
          video
        {% elif is_state_attr("media_player.chromecastultra8714", "app_name", "Videostream'") %}
          video
        {% elif is_state_attr("media_player.chromecastultra8714", "app_name", "Spotify") %}
          music
        {% elif is_state_attr("media_player.chromecastultra8714", "app_name", "SoundCloud") %}
          music
        {% else %}
          main
        {% endif %}