#################################################################
## Sensors Hue
#################################################################

- platform: hue

- platform: rest
  resource: !secret kitchen_motion_url
  value_template: '{{ value_json.state.status }}'
  scan_interval: 2
  name: 'Kitchen Motion'

- platform: rest
  resource: !secret hallfront_motion_url
  value_template: '{{ value_json.state.status }}'
  scan_interval: 2
  name: 'Hall Frontdoor Motion'

- platform: rest
  resource: !secret hallkitchen_motion_url
  value_template: '{{ value_json.state.status }}'
  scan_interval: 2
  name: 'Hall Kitchen Motion'

- platform: rest
  resource: !secret living_motion_url
  value_template: '{{ value_json.state.status }}'
  scan_interval: 2
  name: 'Livingroom Motion'