#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: numeric_state
      entity_id: 'sensor.bathhydro_humidity'
      above: '{{ states.input_number.bathroom_humidity_level.state | int }}'
    - platform: state
      to: 'on'
      entity_id: light.gang_onder_1
  condition:
    condition: time
    after: '06:00:00'
    before: '23:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: numeric_state
      entity_id: 'sensor.bathhydro_humidity'
      below: '{{ states.input_number.bathroom_humidity_level.state | int }}'
    - platform: state
      entity_id: light.gang_onder_1
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: 'sensor.bathhydro_humidity'
      below: '{{ states.input_number.bathroom_humidity_level.state | int }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.douche_ventilatie
