#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: threshold
      value_template: >-
        {%- if is_state_attr("sensor.bathhydro_temperature", "Humidity status", "wet") -%}
          true
        {%- endif -%}
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: template
      value_template: >-
        {%- if is_state_attr("sensor.bathhydro_temperature", "Humidity status", "comfort") -%}
          true
        {%- endif -%}
  action:
    - service: homeassistant.turn_off
      entity_id: switch.douche_ventilatie
