#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: threshold
      entity_id: sensor.bathhydro_humidity
      upper: 70
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: threshold
      entity_id: sensor.bathhydro_humidity
      lower: 70
  action:
    - service: homeassistant.turn_off
      entity_id: switch.douche_ventilatie
