#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: numeric_state
      entity_id: 'sensor.bathhydro_humidity'
      above: 65
    - platform: state
      to: 'on'
      entity_id: light.badkamer
  condition:
    condition: time
    after: '07:00:00'
    before: '18:30:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: numeric_state
      entity_id: 'sensor.bathhydro_humidity'
      below: 75
    - platform: state
      entity_id: light.badkamer
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: 'sensor.bathhydro_humidity'
      below: 75
  action:
    - service: homeassistant.turn_off
      entity_id: switch.douche_ventilatie
