#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: template
      value_template: >-
        {%- if is_state_attr("sensor.bathhydro_temperature", "Humidity status", "wet") -%}
          true
        {%- endif -%}
    - platform: state
      to: 'on'
      entity_id: light.gang_onder_1
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: template
      value_template: >-
        {%- if is_state_attr("sensor.bathhydro_temperature", "Humidity status", "comfort") -%}
          true
        {%- endif -%}
    - platform: state
      entity_id: light.gang_onder_1
      to: 'off'
#      for:
#        minutes: 5
  condition:
    - condition: numeric_state
      entity_id: 'sensor.bathhydro_humidity'
      below: '70'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.douche_ventilatie
