#################################################################
## Automations Bedroom
#################################################################

- alias: Mosquito livingroom on
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.overig_pw

- alias: Mosquito livingroom off
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.overig_pw