#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
#  automatic_add: True
  devices:
    0a5207377d0e00a83e0169:
      name: BathHydro
      data_type:
        - Humidity
        - Temperature


- platform: statistics
  name: Humidity_stats
  entity_id: sensor.bathhydro_humidity
  max_age:
    minutes: 90

- platform: template
    sensors:
      humidity_min:
        friendly_name: "MinHumidity"
        value_template: '{{ states.sensor.bathhydro_humidity.attributes.min_value + 5 }}'