#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
  devices:
    0b110002008b25e202000050:
      name: een
    0b110001008b25e201000050:
      name: twee
    0b1100000135987e0a000050:
      name: drie