#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
#  automatic_add: True
  devices:
    0a5207377d0e00a83e0169:
      name: BathHydro
      data_type:
        - Humidity
        - Temperature

- platform: template
  sensors:
    humidity_minimal:
      friendly_name: humidity_minimal
      value_template: '{% if states.sensor.bathhydro_humidity.last_updated is undefined %}{{"00:00:00"}}{% else %}{{ ((as_timestamp(states.sensor.humidity_minimal.last_updated)-as_timestamp(states.sensor.bathhydro_humidity.last_updated)).seconds) }}{% endif %}'
      entity_id:
        - sensor.humidity_minimal