#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
  devices:
    085002023f0100cc49:
      name: Bath
      fire_event: True
      data_type:
       - Humidity
       - Temperature