#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
  automatic_add: True
  devices:
    0a5207377d0e00a83e0169:
      name: BathHydro