#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
#  automatic_add: True
  devices:
    0a5207377d0e00a83e0169:
      name: BathHydro
      data_type:
        - Humidity
        - Temperature
        - Humidity status


- platform: statistics
  name: Humidity_stats
  entity_id: sensor.bathhydro_humidity
  data_type:
    - min_value
  max_age:
    minutes: 90