#################################################################
## Sensors Bath Temperature and Hydro
#################################################################

- platform: rfxtrx
  automatic_add: True