#################################################################
## Sensors Lux
#################################################################

- platform: rest
  resource: !secret kitchen_lux_url
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Kitchen Lux'

- platform: rest
  resource: !secret hallfront_lux_url
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Hall Frontdoor Lux'

- platform: rest
  resource: !secret hallkitchen_lux_url
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Hall Kitchen Lux'

- platform: rest
  resource: !secret living_lux_url
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Livingroom Lux'

- platform: rest
  resource: !secret bath_lux_url
  value_template: '{{ (10 ** (float(value_json.state.lightlevel - 1) / 10000))|round(1) }}'
  unit_of_measurement: Lux
  name: 'Bathroom Lux'