- platform: yr

- platform: rest
  resource: !secret kitchen_temp_url
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: 째C
  name: 'Kitchen Temperature'

- platform: rest
  resource: !secret hallfront_temp_url         
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: 째C
  name: 'Hall Frontdoor Temperature'

- platform: rest
  resource: !secret hallkitchen_temp_url         
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: 째C
  name: 'Hall Kitchen Temperature'

- platform: rest
  resource: !secret living_temp_url         
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: 째C
  name: 'Livingroom Temperature'

- platform: rest
  resource: !secret kitchen_lux_url
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Kitchen Lux'

- platform: rest
  resource: !secret hallfront_lux_url
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Hall Frontdoor Lux'

- platform: rest
  resource: !secret hallkitchen_lux_url
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Hall Kitchen Lux'

- platform: rest
  resource: !secret living_lux_url
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Livingroom Lux'
