#################################################################
## Automations
#################################################################

  - alias: "Media player paused/stopped"
    trigger:
      - platform: state
        entity_id: media_player.entertainment_area
        from: 'playing'
        to: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
        service: light.turn_off
        entity_id: light.zithoek

  - alias: "Media player playing"
    trigger:
      - platform: state
        entity_id: media_player.entertainment_area
        to: 'playing'
        from: 'idle'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
        service: light.turn_off
        entity_id: light.zithoek  
