#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathhydro_temperature
      value_template: '{{ Humidity }}'
      above: 62
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathhydro_temperature
      value_template: '{{ Humidity }}'
      below: 62
  action:
    - service: homeassistant.turn_off
      entity_id: switch.switch.douche_ventilatie
