#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: template
      value_template: >-
        {% if states('sensor.humidity_stats_mean.attributes.min_value.state + 5') < states('sensor.bathhydro_humidity.state') %}
          true
        {%- endif -%}
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: template
      value_template: >-
        {% if states('sensor.humidity_stats_mean.attributes.min_value.state + 5') > states('sensor.bathhydro_humidity.state') %}
          true
        {%- endif -%}
  action:
    - service: homeassistant.turn_off
      entity_id: switch.douche_ventilatie
