#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathhydro_temperature
#      value_template: '{{ state.attributes.humidity }}'
      above: 25
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathhydro_temperature
 #     value_template: '{{ state.attributes.humidity }}'
      below: 25
  action:
    - service: homeassistant.turn_off
      entity_id: switch.douche_ventilatie
