#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: state
      entity_id: sensor.bathhydro_temperature
      value_template: >-
        {%- if is_state_attr("sensor.bathhydro_temperature", "Humidity") | float > 60 -%}
          true
        {%- endif -%}
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie
