#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: state
      entity_id: sensor.bathhydro_temperature.humidity
      above: 60
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie
