#################################################################
## Automations Bathroom
#################################################################

- alias: Ventilator en spiegelverwarming aan
  trigger:
    - platform: template
      value_template: '{{ sensor.humidity_stats_mean.attributes.min_value.state + 5 < sensor.bathhydro_humidity.state}}'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.douche_ventilatie

- alias: Ventilator en spiegelverwarming uit
  trigger:
    - platform: template
      value_template: '{{ sensor.humidity_stats_mean.attributes.min_value.state + 5 > sensor.bathhydro_humidity.state}}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.douche_ventilatie
