#################################################################
## Automation Hue Living
#################################################################

- alias: Turn on living light when there is movement
  trigger:
    - platform: state
      entity_id: sensor.living_motion
      state: '1'
  condition:
    condition: time
    after: '07:00:00'
    before: '23:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.living_light_group

- alias: Turn off hall light 5 minutes after last movement
  trigger:
    - platform: state
      entity_id: sensor.living_motion
      state: '0'
      for:
        minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: group.living_group


