#################################################################
## Automation Hue Living
#################################################################

- alias: Turn on living light when there is movement
  trigger:
    - platform: state
      entity_id: sensor.livingroom_motion
      state: '1'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.livingroom_lux
        below: 160
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_normal

- alias: Turn off living light 30 minutes after last movement
  trigger:
    - platform: state
      entity_id: sensor.livingroom_motion
      state: '0'
      for:
        minutes: 30
  condition:
    condition: state
    entity_id: media_player.entertainment_area
    state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: group.living_light_group

- alias: Turn off living corner light 30 minutes after last movement
  trigger:
    - platform: state
      entity_id: sensor.livingroom_motion
      state: '0'
      for:
        minutes: 30
  condition:
    condition: state
    entity_id: media_player.entertainment_area
    state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corneroff

