#################################################################
## Automation Hue Kitchen
#################################################################

- alias: Turn on kitchen light when there is movement
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion
    state: '1'
  condition:
    condition: numeric_state
    entity_id: sensor.kitchen_lux
    below: 18
  action:
    service: homeassistant.turn_on
    entity_id: light.keuken

- alias: Turn off kitchen light 2 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion
    state: '0'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: light.keuken

- alias: If motion continuously active set a timer to check for lux
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.kitchen_motion
        state: '1'
      - condition: numeric_state
        entity_id: sensor.kitchen_lux
        below: 18
      - condition: state
        entity_id: light.keuken
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.keuken


