#################################################################
## Automation Hue Kitchen
#################################################################

- alias: Turn on kitchen light when there is movement
  trigger:
    - platform: state
      entity_id: sensor.kitchen_motion
      state: '1'
    - platform: state
      state: 'paused'
      entity_id: media_player.entertainment_area
  condition:
    condition: numeric_state
    entity_id: sensor.kitchen_lux
    below: 160
  action:
    service: homeassistant.turn_on
    entity_id: scene.kitchen_normal

- alias: Turn off kitchen light 10 minutes
  trigger:
    - platform: state
      entity_id: sensor.kitchen_motion
      state: '0'
      for:
        minutes: 10
  condition: 
    condition: state
    entity_id: media_player.entertainment_area
    state: 'off'
  action:
  #  service: homeassistant.turn_on
  #  entity_id: script.turn_off_with_step
    service: homeassistant.turn_off
    entity_id: light.keuken

- alias: Entertainment area playing netflix motion sensor
  trigger:
    - platform: state
      entity_id: sensor.kitchen_motion
      state: '0'
      for:
        minutes: 1
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.kitchen_lux
        below: 160  
      - condition: template
        value_template: >-
          {%- if is_state_attr("media_player.entertainment_area", "app_name", "Netflix") -%}
            true
          {%- endif -%}
  action:
    service: homeassistant.turn_on
    entity_id: scene.kitchen_netflix


- alias: Entertainment area playing netflix kitchen light
  trigger:
    - platform: state
      state: 'playing'
      entity_id: media_player.entertainment_area
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.kitchen_lux
        below: 160  
      - condition: state
        entity_id: sensor.kitchen_motion
        state: '0'
  action:
    service: homeassistant.turn_on
    entity_id: scene.kitchen_netflix


