#################################################################
## Automation Hue Living
#################################################################

- alias: Turn on living light when there is movement
  trigger:
    - platform: state
      entity_id: sensor.livingroom_motion
      state: '1'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_normal

- alias: Turn off living light 15 minutes after last movement
  trigger:
    - platform: state
      entity_id: sensor.livingroom_motion
      state: '0'
      for:
        minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: group.living_light_group

