#################################################################
## Automation Living Corner Light
#################################################################

- alias: Cornerlight Weather prediction clear day
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Clear'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Partly Cloudy'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Mostly Cloudy'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_clear_day


- alias: Cornerlight Weather prediction rain
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Rain'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Chance of Showers'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Showers'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Chance of Rain'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_rain


- alias: Cornerlight Weather prediction snow and sleet
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Blowing Snow'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Very Cold'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'OMITTED'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Flurries'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Chance of Snow Showers'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Chance of Ice Pellets'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Ice Pellets'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Blizard'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Snow Showers'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Chance of Snow'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Snow'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_snow


- alias: Cornerlight Weather prediction Drizzle
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Cloudy'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Hazy'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Foggy'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_wind

- alias: Cornerlight Weather prediction thunderstorm
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Chance of a Thunderstorm'
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Thunderstorm'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_thunderstorm

- alias: Cornerlight Weather prediction hot
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.pws_weather_1h
            state: 'Very Hot'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_hot