#################################################################
## Automation Living Corner Light
#################################################################

- alias: Cornerlight Weather prediction clear day
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: state
        entity_id: sensor.pws_weather_1h
        state: 'Clear'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_clear_day


- alias: Cornerlight Weather prediction rain
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: state
        entity_id: sensor.pws_weather_1h
        state: 'Rain'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_rain


- alias: Cornerlight Weather prediction snow and sleet
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: state
        entity_id: sensor.pws_weather_1h
        state: 'Snow'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_snow


- alias: Cornerlight Weather prediction Drizzle
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: state
        entity_id: sensor.pws_weather_1h
        state: 'Drizzle'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_wind


- alias: Cornerlight Weather prediction fog
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: state
        entity_id: sensor.pws_weather_1h
        state: 'Fog'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_fog


- alias: Cornerlight Weather prediction partly cloudy
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: state
        entity_id: sensor.pws_weather_1h
        state: 'Partly Cloudy'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_cloudy


- alias: Cornerlight Weather prediction mostly cloudy day
  trigger:
    - platform: state
      entity_id: switch.motion_kaku_living
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.entertainment_area
        state: 'off'
      - condition: state
        entity_id: sensor.dark_sky_icon
        state: 'Mostly Cloudy'
  action:
    service: homeassistant.turn_on
    entity_id: scene.living_corner_partly_cloudy_day